//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aramak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int PizzaIDD { get; set; }
        public string Type { get; set; }
        public string Size { get; set; }
        public string Topping { get; set; }
        public string CustomerName { get; set; }
        public string TotalCost { get; set; }
    }
}
