//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aramak
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIZZA2
    {
        public int Pizza2ID { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
