//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aramak
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PIZZADATABASEEntities : DbContext
    {
        public PIZZADATABASEEntities()
            : base("name=PIZZADATABASEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<PIZZA> PIZZAs { get; set; }
        public virtual DbSet<PIZZA2> PIZZA2 { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
    }
}
