//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aramak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int TransactionsID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<System.DateTime> DateOrderPlaced { get; set; }
    }
}
